// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"
	events "cqrseventsourcingbar/events"

	ksuid "github.com/segmentio/ksuid"

	mock "github.com/stretchr/testify/mock"
)

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

// LoadAllEvents provides a mock function with given fields: ctx
func (_m *EventStore) LoadAllEvents(ctx context.Context) ([]events.Event, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAllEvents")
	}

	var r0 []events.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]events.Event, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []events.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]events.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadEvents provides a mock function with given fields: ctx, aggregateID
func (_m *EventStore) LoadEvents(ctx context.Context, aggregateID ksuid.KSUID) ([]events.Event, error) {
	ret := _m.Called(ctx, aggregateID)

	if len(ret) == 0 {
		panic("no return value specified for LoadEvents")
	}

	var r0 []events.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ksuid.KSUID) ([]events.Event, error)); ok {
		return rf(ctx, aggregateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ksuid.KSUID) []events.Event); ok {
		r0 = rf(ctx, aggregateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]events.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ksuid.KSUID) error); ok {
		r1 = rf(ctx, aggregateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveEvents provides a mock function with given fields: ctx, aggregateID, previousEventCount, _a3
func (_m *EventStore) SaveEvents(ctx context.Context, aggregateID ksuid.KSUID, previousEventCount int, _a3 []events.Event) error {
	ret := _m.Called(ctx, aggregateID, previousEventCount, _a3)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ksuid.KSUID, int, []events.Event) error); ok {
		r0 = rf(ctx, aggregateID, previousEventCount, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventStore creates a new instance of EventStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventStore {
	mock := &EventStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
